#!/bin/sh
set -e

distro=$(lsb_release -d | awk '{print $2}')

setup_golang_debian() {
	if ! which go version > /dev/null; then
		wget https://golang.org/dl/go1.18.3.linux-amd64.tar.gz
		sudo tar -zxvf go1.18.3.linux-amd64.tar.gz -C /usr/local

		echo "export PATH=/usr/local/go/bin:${PATH}" >> ~/.bashrc
		$(source ~/.bashrc)
		$(rm -rf go1.18.13.linux-amd64.tar.gz)
	else
		echo "installed package"
	fi
}

if [ $distro = "Oracle" ]; then
	if ! which smbclient > /dev/null; then
		sudo yum install -y samba samba-client
	else
		echo "installed package"
	fi

	if ! sudo which mount.cifs > /dev/null; then
		sudo yum install -y cifs-utils
	else
		echo "installed package"
	fi

elif [ $distro = "Debian" ]; then
	if ! which smbclient > /dev/null ; then
		sudo apt install samba smbclient
	else
		echo "installed package"
	fi

	if ! sudo which mount.cifs > /dev/null; then
		sudo apt install cifs-utils
	else
		echo "installed package"
	fi
else
	echo "unregistered distro"
fi

setup_golang_debian
