#!/bin/sh
set -e

distro=$(lsb_release -d | awk '{print $2}')
repo=https://github.com/karchx/ftpsmb

setup_golang_debian() {
	if ! which go version > /dev/null; then
		wget https://golang.org/dl/go1.18.3.linux-amd64.tar.gz
		sudo tar -zxvf go1.18.3.linux-amd64.tar.gz -C /usr/local

		echo "export PATH=/usr/local/go/bin:${PATH}" >> ~/.bashrc
		$(source ~/.bashrc)
		$(rm -rf go1.18.13.linux-amd64.tar.gz)
	else
		echo "installed package"
	fi
}

if [ $distro = "Oracle" ]; then
	if ! which smbclient > /dev/null; then
		read -p "Desea instalar smbclinet? [Y/n] " response
		if [ $response = "Y" ]; then
			sudo yum install -y samba samba-client
		fi
	else
		echo "installed package"
	fi

	if ! sudo which mount.cifs > /dev/null; then
		read -p "Desea instalar cifs-utils? [Y/n] " response
		if [ $response = "Y" ]; then
			sudo yum install -y cifs-utils
		fi
	else
		echo "installed package"
	fi

elif [ $distro = "Debian" ]; then
	if ! which smbclient > /dev/null ; then
		read -p "Desea instalar smbclient? [Y/n] " response
		if [ $response = "Y" ]; then
			sudo apt install -y samba smbclient
		fi
	else
		echo "installed package"
	fi

	if ! sudo which mount.cifs > /dev/null; then
		read -p "Desea instalar cifs-utils? [Y/n] " response
		if [ $response = "Y" ]; then
			sudo apt install -y cifs-utils
		fi
	else
		echo "installed package"
	fi
else
	echo "unregistered distro"
fi

echo "Downloading project..."
git clone $repo 

echo "Make ftp..."
cd ftpsmb
go build -o ftp

echo "Removed trash..."
cd ../
rm -rf ftpsmb

echo "Make binary"
sudo mv ftp /usr/bin